---
title: "loop functions ggplot"
author: "DS"
date: '2022-11-26'
output: html_document
---

```{r}
library('dplyr')
plot_region <- function(x = "1"){
  tmp <- before_russia_regions %>%
    filter(VARNAME_1 == x)
    p <- ggplot(tmp, aes(x = week ,y = All_case_deaths ,group = Year))+
    geom_line(color = "grey75", alpha = 0.6)+
    labs(
    x = "Weeks", 
    y = "Deaths",
    title = "Death rates historical averages",
    subtitle = "Number of deaths per weeks from all causes in 2020")+
  geom_line(
    data = pandemia_russia_regions2020 %>% 
      filter(VARNAME_1 == x),
    color = "firebrick"
  )+geom_ribbon(
    data = pandemia_russia_regions2020 %>% 
      filter(VARNAME_1 == x),
    aes(ymin = pmin(expectdeaths, All_case_deaths), ymax = All_case_deaths, 
    ), 
    fill = "tomato", 
    alpha = 0.5
  )+geom_line(
    data = pandemia_russia_regions2020 %>% 
      filter(VARNAME_1 == x),aes(
    color = "All_case_deaths")
  )+
  geom_line(
    data = pandemia_russia_regions2020 %>% 
      filter(VARNAME_1 == x),
    aes(x = week,y = expectdeaths,
    color = "Expect_deaths"),
    inherit.aes = FALSE 
  )+
     scale_color_manual(name = "Y series", values = c("All_case_deaths" = "blue", "Expect_deaths" = "black","Excess_deaths" = "tomato", "Past_Years" = "grey75"))+
     ft_theme()+theme_classic()+theme(legend.position = "bottom")
  
   
   
  ggsave(p,file = paste0(x,".pdf"),dpi = 300,limitsize = FALSE)
  }
for (k in unique(before_russia_regions$VARNAME_1)) {
  plot_region(k)
}
```


```{r}
setwd("C:/Users/AVGUST/Desktop/R_ regions/2021new")
#setwd("C:/Users/AVGUST/Desktop/R_ regions/2021")
plot_region <- function(x = "1"){
  tmp <- pandemia_russia_regions2020_before_russia %>% 
    filter(VARNAME_1 == x)
   p <- ggplot(tmp, aes(x = week ,y = All_case_deaths ,group = Year))+
    geom_line(color = "grey75", alpha = 0.6)+
    labs(
    x = "Weeks", 
    y = "Deaths",
    title = "Death rates historical averages",
    subtitle = "Number of deaths per weeks from all causes in 2021")+
  geom_line(
    data = pandemia_russia_regions2021 %>% 
      filter(VARNAME_1 == x),
    color = "firebrick"
  )+geom_ribbon(
    data = pandemia_russia_regions2021 %>% 
      filter(VARNAME_1 == x),
    aes(ymin = pmin(expectdeaths, All_case_deaths), ymax = All_case_deaths, 
    ), 
    fill = "tomato", 
    alpha = 0.5
  )+geom_line(
    data = pandemia_russia_regions2021 %>% 
      filter(VARNAME_1 == x),aes(
    color = "All_case_deaths")
  )+
  geom_line(
    data = pandemia_russia_regions2021 %>% 
      filter(VARNAME_1 == x),
    aes(x = week,y = expectdeaths,
    color = "Expect_deaths"),
    inherit.aes = FALSE 
  )+
     scale_color_manual(name = "Y series", values = c("All_case_deaths" = "blue", "Expect_deaths" = "black","Excess_deaths" = "tomato", "Past_Year" = "grey75"))+
   ft_theme()+theme_classic()+theme(legend.position = "bottom")
  ggsave(p,file = paste0(x,".pdf"),dpi = 300,limitsize = FALSE)
  }
for (k in unique(pandemia_russia_regions2020_before_russia$VARNAME_1)) {
  plot_region(k)
}
```

```{r}
setwd("C:/Users/AVGUST/Desktop/R_ regions/all_new")
#setwd("C:/Users/AVGUST/Desktop/R_ regions/All")
plot_region <- function(x = "1"){
  al <- before_russia_regions %>% 
    filter(VARNAME_1 == x)
    z <- ggplot(al, aes(x = week ,y = All_case_deaths ,group = Year)
) +
  geom_line(color = "black", alpha = 0.6)+
    labs(
    x = "Weeks", 
    y = "Deaths",
    title = "Death rates in Russia historical averages",
    subtitle = "Number of deaths per weeks from all causes"
  )+
  geom_smooth(formula = y ~ x, method = "loess",col='red', size=1)+
  facet_wrap(vars(Year), scales = "free_y")+
  ft_theme()+theme_classic()+theme(legend.position = "bottom")
    ggsave(z,file = paste0(x,".pdf"),dpi = 300,limitsize = FALSE)
}
for (k in unique(before_russia_regions$VARNAME_1)) {
  plot_region(k)
}  

```
